package shapeless

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "2.3.3-SNAPSHOT". */
  val version: String = "2.3.3-SNAPSHOT"
  /** The value is "2.12.1". */
  val scalaVersion: String = "2.12.1"
  /** The value is Some("0c01f218a76c20cce706a031aba46eadaaf65988"). */
  val gitHeadCommit: Option[String] = Some("0c01f218a76c20cce706a031aba46eadaaf65988")
  /** The value is "2017-01-17 21:06:31.282". */
  val builtAtString: String = "2017-01-17 21:06:31.282"
  /** The value is 1484687191282L. */
  val builtAtMillis: Long = 1484687191282L
  override val toString: String = {
    "version: %s, scalaVersion: %s, gitHeadCommit: %s, builtAtString: %s, builtAtMillis: %s" format (
      version, scalaVersion, gitHeadCommit, builtAtString, builtAtMillis
    )
  }
}
